# -*- coding: utf-8 -*-
"""object_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wQna86em-8TDk059GjGCxvr2H9v7Vdss
"""

!pip install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl

from google.colab import drive
drive.mount('/content/drive')

"""#This model is trained to detect and recognize 80 different objects, named below:

person, bicycle, car, motorcycle, airplane,
bus, train, truck, boat, traffic light, fire hydrant, stop_sign,
parking meter, bench, bird, cat, dog, horse, sheep, cow, elephant, bear, zebra,
giraffe, backpack, umbrella, handbag, tie, suitcase, frisbee, skis, snowboard,
sports ball, kite, baseball bat, baseball glove, skateboard, surfboard, tennis racket,
bottle, wine glass, cup, fork, knife, spoon, bowl, banana, apple, sandwich, orange,
broccoli, carrot, hot dog, pizza, donot, cake, chair, couch, potted plant, bed,
dining table, toilet, tv, laptop, mouse, remote, keyboard, cell phone, microwave,
oven, toaster, sink, refrigerator, book, clock, vase, scissors, teddy bear, hair dryer,
toothbrush.
"""

#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()


from imageai.Detection import VideoObjectDetection
import os

#execution_path = os.getcwd()

detector = VideoObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( "/content/drive/My Drive/Colab Notebooks/yolo.h5")
detector.loadModel()

video_path = detector.detectObjectsFromVideo(input_file_path="/content/Crow fly (slow motion).mp4",output_file_path="/content/bird1.mp4"
                                , frames_per_second=25, log_progress=True)
print(video_path)



